data_dir: ./data/ethical_safeguards/
dataset_file: do-not-answer-data.jsonl
t: 1 # temperature
n: 1  # number of generation per API call
max_tokens: 150

#out_file: ./results/ethical_safeguards/together/phi-2/do_not_answer_results.jsonl
#out_file: ./results/ethical_safeguards/together/RedPajama-INCITE-Chat-3B-v1/do_not_answer_results.jsonl
out_file: ./results/ethical_safeguards/together/gemma/do_not_answer_results.jsonl