## Model Config for LLAMA-2
#model: "together/Llama-2-7b-chat-hf"
#type: CHAT
#conv_template: "llama-2"
#
#model_loader: HF
#torch_dtype: BFLOAT16
#quant_file: null
#tokenizer_name: null
#trust_remote_code: true
#use_auth_token: true

# Model Config for GEMMA
model: "together/gemma-2b-it"
type: CHAT
conv_template: "gemma"

model_loader: HF
torch_dtype: BFLOAT16
quant_file: null
tokenizer_name: null
trust_remote_code: true
use_auth_token: true

## Model Config for Mistral
#model: "together/Mistral-7B-Instruct-v0.2"
#type: CHAT
#conv_template: "mistral"

#model_loader: HF
#torch_dtype: BFLOAT16
#quant_file: null
#tokenizer_name: null
#trust_remote_code: true
#use_auth_token: true

## Model Config for RedPajama
#model: "together/RedPajama-INCITE-Chat-3B-v1"
#type: CHAT
#conv_template: "redpajama-incite"

#model_loader: HF
#torch_dtype: BFLOAT16
#quant_file: null
#tokenizer_name: null
#trust_remote_code: true
#use_auth_token: true
